### PR TITLE
Update to GNOME 47 and others

### PR DESCRIPTION
**Pull request by hfiguiere**
GNOME 45 is EOL

Close #10

### CODE REVIEW

**Comment by hfiguiere** [comment]
it's a GNOME infra failure.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
Patch submitted upstream https://gitlab.com/entangle/entangle/-/merge_requests/62

**Comment by ghost** [comment]
The EOL warning has not disappeared.

over 4 years ago (Built about 1 year ago)

```
Uses an end-of-life runtime
The runtime used by this app is no longer receiving security updates
```

**Pull request merged**
